from ac_eng import *


# Aircraft-engine specific replacements (takeoff)
TAKEOFF_REPLACEMENTS = {}
TAKEOFF_REPLACEMENTS[AC_ENG_737_300_22K] = {
    "MAX BRAKE RELEASE WT MUST NOT EXCEED MAX CERT TAKEOFF WT OF      XXXXX KG": "",
}

TAKEOFF_REPLACEMENTS[AC_ENG_772_TRENT884] = {
    "MAX BRAKE RELEASE WT MUST NOT EXCEED MAX CERT TAKEOFF WT OF      YYYYY KG": "",
    "XXXXXXXX": "YYYYY",
}


# Aircraft-engine specific replacements (landing)
LANDING_REPLACEMENTS = {}
LANDING_REPLACEMENTS[AC_ENG_737_300_22K] = {
    "Landing weight must not exceed   XXXXX KG": "",
}

LANDING_REPLACEMENTS[AC_ENG_772_TRENT884] = LANDING_REPLACEMENTS[AC_ENG_737_300_22K]
